name: CI/CD
on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

  pull_request:
    branches:
      - master
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run Unit Tests
        run: |
          echo Starting tests...
          ./gradlew test

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run a one-line script
        run: ./gradlew build

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Deploy to Dev
        run: echo implement deploy to Dev